version: '3.7'

services:
  db:
    image: postgres:13
    restart: always
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
      - PGPORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: app
    restart: always
    ports:
      - 5050:5050
    environment:
      - DEBUG=0
    networks:
      - flask_network
    depends_on:
      - 'db'
    command: ["./wait-for-it.sh","db:5432","--","./start_app.sh"]

networks:
  flask_network:

volumes:
  postgres_data: